name: Generate GitHub Metrics and Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

  generate-summary-cards:
    name: Generate Profile Summary Cards
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: kautukkundan/github-profile-summary-cards@v1
        with:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }} # Use the same token if permissions allow, or create a dedicated one

  # generate-wakatime: # Uncomment this section after setting up WakaTime
  #   name: Generate WakaTime Stats
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: anmol098/waka-readme-stats@master # Use the latest version if preferred
  #       with:
  #         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Needs WAKATIME_API_KEY secret
  #         GH_TOKEN: ${{ secrets.METRICS_TOKEN }} # Needs GH_TOKEN secret (can use METRICS_TOKEN)
  #         SHOW_PROFILE_VIEWS: "False" # Optional: Adjust settings as needed
  #         SHOW_TOTAL_CODE_TIME: "True" # Optional
  #         SHOW_DAYS_OF_WEEK: "False" # Optional
  #         SHOW_PROJECTS: "False" # Optional
  #         SHOW_LANGUAGE_PER_REPO: "False" # Optional
  #         SHOW_LOC_CHART: "False" # Optional

  generate-snake:
    runs-on: ubuntu-latest
    steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        
        -   name: Generate Snake
            uses: Platane/snk@v3
            with:
                github_user_name: ${{ github.repository_owner }}
                outputs: |
                    dist/github-snake.svg
                    dist/github-snake-dark.svg?palette=github-dark
                    dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        -   name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: snake-graphics
                path: dist

        -   name: Push to GitHub
            run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add dist
                git commit -m "Update snake graphics"
                git push

  generate-activity:
    name: Generate Recent Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }} # Or a dedicated token
