name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Devasy23
          svg_out_path: dist/github-snake.svg
          svg_out_path_dark: dist/github-snake-dark.svg

      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}